[colors.primary]
background = '#0f1417'
foreground = '#dfe3e7'

[colors.selection]
text = '#dfe3e7'
background = '#004c6b'

[colors.cursor]
text = '#0f1417'
cursor = '#92cef5'

[colors.normal]
black   = '#0f1417'
red     = '#e64c4a'
green   = '#73d66e'
yellow  = '#dbcf7b'
blue    = '#488ab4'
magenta = '#7ca0b7'
cyan    = '#92cef5'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f62'
green   = '#8ae086'
yellow  = '#e8de97'
blue    = '#9cdcff'
magenta = '#3d8395'
cyan    = '#5c7ca0'
white   = '#ffffff'
