[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.selection]
text = '#e2e2e9'
background = '#2b4678'

[colors.cursor]
text = '#111318'
cursor = '#adc6ff'

[colors.normal]
black   = '#111318'
red     = '#e54d45'
green   = '#6fd66e'
yellow  = '#dbd27b'
blue    = '#6180d1'
magenta = '#8e9dbf'
cyan    = '#adc6ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0605f'
green   = '#86e086'
yellow  = '#e8e197'
blue    = '#b9d4ff'
magenta = '#517bac'
cyan    = '#6b75b3'
white   = '#ffffff'
