[colors.primary]
background = '#101510'
foreground = '#dfe4dc'

[colors.selection]
text = '#dfe4dc'
background = '#19512a'

[colors.cursor]
text = '#101510'
cursor = '#9ad4a2'

[colors.normal]
black   = '#101510'
red     = '#e44b61'
green   = '#82d66e'
yellow  = '#dbc07b'
blue    = '#3e9c4b'
magenta = '#7c9f81'
cyan    = '#9ad4a2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f75'
green   = '#97e086'
yellow  = '#e8d297'
blue    = '#a5e3ad'
magenta = '#40893b'
cyan    = '#4b865a'
white   = '#ffffff'
